---
--- 由60addons創建並漢化(https://60addons.com)

if (GetLocale() ~= "zhTW") then
    return
end

local L = WebDKP.translations

--中文職業簡稱
L.CLASS_ALIAS_TO_ENG_MAP["LR"] = "hunter"
L.CLASS_ALIAS_TO_ENG_MAP["QS"] = "paladin"
L.CLASS_ALIAS_TO_ENG_MAP["ZS"] = "warrior"
L.CLASS_ALIAS_TO_ENG_MAP["FS"] = "mage"
L.CLASS_ALIAS_TO_ENG_MAP["SS"] = "warlock"
L.CLASS_ALIAS_TO_ENG_MAP["SM"] = "shaman"
L.CLASS_ALIAS_TO_ENG_MAP["DZ"] = "rogue"
L.CLASS_ALIAS_TO_ENG_MAP["MS"] = "priest"
L.CLASS_ALIAS_TO_ENG_MAP["XD"] = "druid"

--MinimapDropDown
L.WEBDKP_MINIMAPDROPDOWN_DKPTABLE = "DKP表"
L.WEBDKP_MINIMAPDROPDOWN_BIDDING = "競標"
L.WEBDKP_MINIMAPDROPDOWN_TIMEDAWARDS = "時間分獎勵"
L.WEBDKP_MINIMAPDROPDOWN_OPTIONS = "選項"
L.WEBDKP_MINIMAPDROPDOWN_HELP = "幫助"
L.WEBDKP_MINIMAPDROPDOWN_SYNCHSETTINGS = "遊戲內同步設置"
L.WEBDKP_MINIMAPDROPDOWN_VIEWLOG = "獎懲日誌"
L.WEBDKP_MINIMAPDROPDOWN_RAIDLOG = "Raid事件日誌"
L.WEBDKP_MINIMAPDROPDOWN_CHARRAIDLOG = "團隊出勤日誌"

--Table
L.WEBDKP_HEADER = "DKP 表:"
L.WEBDKP_FRAME_NAME_COLUMN = "名字"
L.WEBDKP_FRAME_CLASS_COLUMN = "職業"
L.WEBDKP_FRAME_DKP_COLUMN = "DKP"
L.WEBDKP_FRAME_GUILDRANK_COLUMN = "會階"

--TABS
L.TAB_FILTER = "過濾"
L.TAB_AWARD_DKP = "獎懲DKP"
L.TAB_AWARD_ITEM = "獎懲物品"
L.TAB_STANDBY = "替補"

--TAB FOR FILTER
L.FILTER_HEADER = "過濾:"
L.FILTER_CLASS_WARLOCK = "|cff9482C9術士|r"
L.FILTER_CLASS_WARRIOR = "|cffC79C6E戰士|r"
L.FILTER_CLASS_HUNTER = "|cffABD473獵人|r"
L.FILTER_CLASS_MAGE = "|cff69CCF0法師|r"
L.FILTER_CLASS_PRIEST = "|cffFFFFFF牧師|r"
L.FILTER_CLASS_DRUID = "|cffFF7D0A德魯伊|r"
L.FILTER_CLASS_PALADIN = "|cffF58CBA聖騎士|r"
L.FILTER_CLASS_SHAMAN = "|cff0099FF薩滿祭司|r"
L.FILTER_CLASS_ROGUE = "|cffFFF569潛行者|r"
L.FILTER_CLASS_DEATH_KNIGHT = "|cffC41F3B死亡騎士|r(忽略)"

L.FILTER_CLASS_CASTERS = "遠程法術(|cff69CCF0法|r,|cff9482C9術|r,|cffFFFFFF牧|r,|cff0099FF薩|r,|cffF58CBA騎|r)"
L.FILTER_CLASS_MELEE = "物理近戰(|cffC79C6E戰|r,|cffFFF569賊|r,|cffFF7D0A德|r,|cffABD473獵|r,|cffF58CBA騎|r,|cff0099FF薩|r)"
L.FILTER_CLASS_HEALER = "治療(|cffFFFFFF牧|r,|cffF58CBA騎|r,|cff0099FF薩|r,|cffFF7D0A德|r)"
L.FILTER_CLASS_CHAIN = "鎖甲(|cffABD473獵|r,|cff0099FF薩|r)"
L.FILTER_CLASS_CLOTH = "布甲(|cff69CCF0法|r,|cff9482C9術|r,|cffFFFFFF牧|r)"
L.FILTER_CLASS_LEATHER = "皮甲(|cffFFF569賊|r,|cffFF7D0A德|r)"
L.FILTER_CLASS_PLATE = "板甲(|cffC79C6E戰|r,|cffF58CBA騎|r)"

L.FILTER_CHECK_ALL = "選取所有"
L.FILTER_UNCHECK_ALL = "取消所有"
L.FILTER_ONLY_SHOW_PLAYERS_IN_CURRENT_GROUP = "只顯示當前團隊玩家"
L.FILTER_ONLY_SHOW_PLAYERS_IN_YOUR_GUILD = "只顯示公會成員"
L.FILTER_ONLY_ONLINE_GUILD_MEMBERS = "只顯示線上的公會成員"
L.FILTER_EXCLUDE_ALL_ALTS = "排除所有小號"
L.FILTER_EXCLUDE_ALTS_NOT_IN_PARTY = "排除不在隊伍的小號"
L.FILTER_INCLUDE_STANDBY_PLAYERS = "包括替補玩家"
L.FILTER_LIMIT_TO_STANDBY_PLAYERS = "只顯示替補玩家"

L.DKP_TABLE_SELECT_ALL = "選取所有"
L.DKP_TABLE_DESELECT_ALL = "取消所有"
L.DKP_TABLE_SAVE_LOG = "|cFF0dea38>保存數據文檔<|r"
L.DKP_TABLE_Refresh = "刷新"

--TAB FOR AWARD DKP
L.AWARD_DKP_HEADER = "獎懲DKP:"
L.AWARD_DKP_INFO1 = "先選取左側的玩家\n然後輸入DKP獎懲"
L.AWARD_DKP_DECAY_HEADER = "DKP衰減:(僅適用於實施了DKP衰減制度的公會)"
L.AWARD_DKP_INFO3 = "選取左側的玩家"
L.AWARD_DKP_REASON_LABEL = "原因:"
L.AWARD_DKP_POINTS_LABEL = "點數: (使用負數為扣分)"
L.AWARD_DKP_AWARD_POINTS = "獎懲DKP"
L.AWARD_DKP_DECAY_LABEL = "衰減值:如(.4),(-.4)"
L.AWARD_DKP_DECAY_BUTTON = "衰減"

--TAB FOR AWARD ITEM
L.AWARD_ITEM_HEADER = "獎懲物品:"
L.AWARD_ITEM_INFO1 = "左邊選取要獎懲的玩家\n 下放輸入DKP資訊"
L.AWARD_ITEM_ITEM_NAME_LABEL = "物品名:"
L.AWARD_ITEM_ITEM_COST_LABEL = "物品DKP: (只允許正數)"
L.AWARD_ITEM_ITEM_COST_LABEL2 = ""
L.AWARD_ITEM_AWARD_ITEM = "獎懲！"

--TAB FOR STANDBY
L.STANDBY_HEADER = "替補玩家:"
L.STANDBY_INFO1 = "也可以讓替補人員M你輸入命令:|cFF0dea38我要替補|r\n退出替補M你輸入命令:|cFF0dea38退出替補|r"
L.STANDBY_ADD_STANDBY_LABEL = "玩家名:"
L.STANDBY_ADD_TO_STANDBY = "添加"
L.STANDBY_DEL_STANDBY = "刪除"
L.STANDBY_RESET_STANDBY = "重置"
L.STANDBY_ENABLE_STANDBY_ZEROSUM = "為替補玩家啟用零和規則"
L.STANDBY_ENABLE_STANDBY_TIMED = "為替補玩家啟用時間分獎勵"

--BID
L.BID_TITLE = "WebDKP 競標"
L.BID_ITEM_LABEL = "物品:"
L.BID_STARTING_BID_LABEL = "起始DKP:"
L.BID_TIME_LABEL = "競標/Roll時間:"
L.BID_TIME_HINT = "(秒 - 0為無限制)"
L.BID_BID_BUTTON = "開始競標!"
L.BID_ROLL_BUTTON = "開始Roll!"
L.BID_TOP3_BUTTON = "通知競標前3名"
L.BID_TABLE_HEADER = "收到的競標/Rolls:"
L.BID_TABLE_COLUMN_NAME_LABEL = "名字"
L.BID_TABLE_COLUMN_BID_LABEL = "競標"
L.BID_TABLE_COLUMN_DKP_LABEL = "DKP"
L.BID_TABLE_COLUMN_POST_LABEL = "DKP - 競標"
L.BID_TABLE_COLUMN_ROLL_LABEL = "Rolls"
L.BID_TABLE_COLUMN_SPEC_LABEL = "主/副"
L.BID_TABLE_COLUMN_GUILD_RANK_LABEL = "公會會階"
L.BID_AWARD = "獎勵物品給玩家"
L.FORMAT_MSG_ROLLING_PATTERN = "(.+)擲出(%d+)%（(%d+)%-(%d+)%）"

--Timed Award
L.WEBDKP_TIMEDAWARDFRAME_TITLE = "時間分獎勵"
L.WEBDKP_TIMEDAWARDFRAME_TEXT = "時間分獎勵允許你為 DKP/EP 設置一個時間自動獎勵分"
L.WEBDKP_TIMEDAWARDFRAME_DKP_LABEL = "DKP:"
L.WEBDKP_TIMEDAWARDFRAME_TIME_LABEL = "時間:"
L.WEBDKP_TIMEDAWARDFRAME_TIME_HINT = "(分鐘)"
L.WEBDKP_TIMEDAWARDFRAME_LOOPTIMER_LABEL = "重複獎勵:"
L.WEBDKP_TIMEDAWARDFRAME_RESETBUTTON = "重置"
L.STANDBY_RESET_STANDBY_LABEL = "重置所有替補玩家:"
L.WEBDKP_TIMEDAWARDFRAME_STARTSTOPBUTTON = "開始"
L.WEBDKP_TIMEDAWARDFRAME_MINIBUTTON = "迷你計時器"

--Options
L.WEBDKP_OPTIONSFRAME_TITLE = "WebDKP 設置"
--WebDKP_GeneralOptions_Frame
L.WEBDKP_GENERALOPTIONS_FRAME_TITLE = "一般設置:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO1 = "自動填充物品設置:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO2 = "零和DKP:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO3 = "自動Boss擊殺獎勵:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO4 = "啟用/禁用WebDKP"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO5 = "啟用或禁用Alt+左鍵，彈出競價窗口"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO6 = "非隊伍/團隊玩家遮罩私聊"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO7 = "指定一個DKP封頂"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO8 = "EP / GP:"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAUTOFILLENABLED_LABEL = "自動填充物品名"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAUTOAWARDENABLED_LABEL = "自動彈框啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEZEROSUMENABLED_LABEL = "零和模式啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAWARDBOSSDKP_LABEL = "啟用/禁用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEALTCLICK_LABEL = "Alt+左鍵 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEIGNWHISPERS_LABEL = "遮罩 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEDKPCAP_LABEL = "DKP封頂 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_DKPCAPLIMIT_LABEL = "封頂限制:"
L.WEBDKP_GENERALOPTIONS_FRAME_BOSSDKP_LABEL = "DKP 數:"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEENABLED_LABEL = "WebDKP 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEENABLED_LABEL = "WebDKP 啟用"
--WebDKP_BiddingOptions_Frame
L.WEBDKP_BIDDINGOPTIONS_FRAME_INFO1 = "競標選項:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANNOUNCERAID_LABEL = "通告在團隊警報"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDCONFIRMPOPUP_LABEL = "配置競標獎懲彈出"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDALLOWNEGATIVEBIDS_LABEL1 = "允許負DKP競標"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDALLOWNEGATIVEBIDS_LABEL2 = "(允許人們負數競標)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDFIXEDBIDDING_LABEL1 = "使用固定DKP分數競標"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDFIXEDBIDDING_LABEL2 = "(從固定DKP列表中決定DKP分數)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDNOTIFYLOWBIDS_LABEL1 = "當DKP低了通知競標者"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDNOTIFYLOWBIDS_LABEL2 = "(告訴他們現在你不是最高競標者了)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEAUTOGIVE_LABEL1 = "自動給予裝備"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEAUTOGIVE_LABEL2 = "(謹慎使用！自動給予裝備)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLETURNBASE_LABEL1 = "all in DKP"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLETURNBASE_LABEL2 = "同時啟用在固定競標上"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLESILENTBIDDING_LABEL1 = "靜默"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLESILENTBIDDING_LABEL2 = "不會宣佈誰贏了"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANDROLL_LABEL1 = "競標中監視Roll"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANDROLL_LABEL2 = "專為副天賦裝備檢查"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEALLNEED_LABEL1 = "啟用需求百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEALLNEED_LABEL2 = "為'需求'啟用用戶定義的百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_NEEDDKP_LABEL = "'需求' DKP %:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEFIFTYGREED_LABEL1 = "啟用貪婪百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEFIFTYGREED_LABEL2 = "為'貪婪'啟用用戶定義的百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_GREEDDKP_LABEL = "'貪婪' DKP %:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEDISABLEBID_LABEL1 = "禁用'出價'命令"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEDISABLEBID_LABEL2 = "用戶禁用'出價', 強制使用'主天賦''副天賦'命令"
--WebDKP_BiddingOptions2_Frame
L.WEBDKP_BIDDINGOPTIONS2_FRAME_INFO1 = "競標選項:"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_INFO2 = "單擊圖示設置倍增:"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TOGGLEITEMLEVELEQUATION_LABEL = "啟用物品等級倍增器"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_ITEMLEVELMULT_LABEL = "值 (例如.01):"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TOGGLESLOTLOCMULT_LABEL = "啟用槽位置倍增器"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_HELMBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_NECKBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_SHOULDERSBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_BACKBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_CHESTBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_WRISTBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_HANDSBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_WAISTBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_LEGSBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_FEETBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_FINGERBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TRINKETBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_MAINHANDBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_OFFHANDBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_RANGEDBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_RELICBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TWOHANDBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_ONEHANDBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_OFFHANDWEAPONBUTTON = "測試"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_HELDOFFHANDBUTTON = "測試"
--WebDKP_AnnouncementsOptions_Frame
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO12 = "通告選項:"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO13 = "自定義資訊 - 開始競標"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO14 = "自定義資訊 - 競標期間"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO15 = "自定義資訊 - 結束競標"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO16 = "自定義資訊 - 開始Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO17 = "自定義資訊 - Roll期間"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO18 = "自定義資訊 - 結束Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_TOGGLEANNOUNCEMENTS_LABEL = "禁用所有公告"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITSTARTANNOUNCE_LABEL = "$item = 物品, $time = 時間, $bid = 起始DKP"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITDURINGANNOUNCE_LABEL = "$item = 物品, $time = 時間, $name = 名字, $dkp = DKP"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITENDANNOUNCE_LABEL = "$item = 物品, $name = 名字, $dkp = DKP, $totbid = Tot. Bids"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITSROLLANNOUNCE_LABEL = "$item = 物品, $time = 時間"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITROLLANNOUNCE_LABEL = "$item = 物品, $time = 時間, $name = 名字, $roll = Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITEROLLANNOUNCE_LABEL = "$item = 物品, $name = 名字, $roll = Roll, $roltot = Tot. Rolls"
--WebDKP_ItemSlotFrame
L.WEBDKP_ITEMSLOTFRAME_TITLE = "此處為主文本"
L.WEBDKP_ITEMSLOTFRAME_COST = "倍增值:"
L.WEBDKP_ITEMSLOTFRAME_YES = "接受"
L.WEBDKP_ITEMSLOTFRAME_NO = "取消"
--tab
L.WEBDKP_OPTIONSFRAME_TAB1 = "一般"
L.WEBDKP_OPTIONSFRAME_TAB2 = "競標1"
L.WEBDKP_OPTIONSFRAME_TAB4 = "競標2"
L.WEBDKP_OPTIONSFRAME_TAB3 = "公告"

--Announcments.lua
L.FORMAT_WEBDKP_ITEMAWARD = "WebDKP: $player 給予裝備: $item ,被扣了: $cost DKP"
L.FORMAT_WEBDKP_ITEMAWARDZEROSUM = "WebDKP: $dkp 點DKP被獎懲給所有玩家, 零和規則: $item"
L.FORMAT_WEBDKP_DKPAWARDALL = "WebDKP: $dkp 點DKP給予了所有玩家, 原因: $reason."
L.FORMAT_WEBDKP_DKPAWARDSOME = "WebDKP: $dkp 點DKP給予了所有被選擇的玩家, 原因: $reason. \n接收到的玩家都被密語了."
L.FORMAT_WEBDKP_BIDSTART = "WebDKP: 競標已開始 $item! $time "
L.FORMAT_WEBDKP_BIDEND = "WebDKP: $item 競標已結束, 勝利者為 $name , $dkp dkp"
L.FORMAT_WEBDKP_BIDENDSILENT = "WebDKP: 競標已結束 $item"
L.FORMAT_WEBDKP_ROLLEND = "WebDKP: Roll點已結束 $item , $name 是最高點, 為 $roll"
L.FORMAT_WEBDKP_TIMEDAWARD = "WebDKP: $minutes 分鐘獎勵分, 已給予 $dkp dkp"
L.FORMAT_WEBDKP_BOSSAWARDNUM = "WebDKP: 幹得漂亮! Boss獎勵分: $dkp 已自動給予"
L.FORMAT_WEBDKP_SENDWHISPER = "你被獎懲了 "

--AutoFill.lua
L.FORMAT_FIND_OTHER_ITEM_LOOT = "([^%s]+)獲得了物品：(.+)%。"
L.FORMAT_FIND_PLAYER_SELF = "你"




-- ================================
-- Boss kill list used when UNIT_DIED is detected
-- This is in the format of [Parameter recieved by wow] = name you would like to show on dkp
-- e.g. on the spine of deathing fight, the paramter passed is "Deathwing" but the fight is actually spine of deathing
-- ================================
L.BOSS_KILL_LIST = {
    ["魯西弗隆"] = "魯西弗隆", --MC
    ["基赫納斯"] = "基赫納斯", --MC
    ["瑪格曼達"] = "瑪格曼達", --MC
    ["加爾"] = "加爾", --MC
    ["沙斯拉爾"] = "沙斯拉爾", --MC
    ["迦頓男爵"] = "迦頓男爵", --MC
    ["焚化者古雷曼格"] = "焚化者古雷曼格", --MC
    ["薩弗隆先驅者"] = "薩弗隆先驅者", --MC
    ["拉格納羅斯"] = "拉格納羅斯", --MC
    ["管理者埃克索圖斯"] = "管理者埃克索圖斯", --MC
    ["奧妮克希亞"] = "奧妮克希亞", --Onyxia's Lair
};

L.BOSS_YELL_LIST = {
    ["管理者埃克索圖斯"] = {
        ["不……不可能！等一下……我投降！我投降！"] = "管理者埃克索圖斯" },
}

L.BOSS_MAP = {
    ["熔火之心"] = "BossDKPMCAndOLValue",
    ["奧妮克希亞的巢穴"] = "BossDKPMCAndOLValue",
    ["黑翼之巢"] = "BossDKPBWLValue",
    ["安其拉"] = "BossDKPTAQValue",
    ["納克薩瑪斯"] = "BossDKPNAXXValue",
}